### PR TITLE
Package satysfi-cancel.0.0.0

### PR DESCRIPTION
**Pull request by yuhr**
### `satysfi-cancel.0.0.0`
The cancel package
The SATySFi equivalent of the LateX's cancel package.

---
* Homepage: https://github.com/yuhr/satysfi-cancel
* Source repo: git+https://github.com/yuhr/satysfi-cancel.git
* Bug tracker: https://github.com/yuhr/satysfi-cancel/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by na4zagin3** [comment]
@yuhr Thank you for sending this PR!
Could you please add `satysfi-cancel` to `PACKAGES_FOR_STABLE` in `.travis.yml`?

**Comment by yuhr** [comment]
Done 🚀 
By the way, what's the env var `PACKAGES_FOR_STABLE`? Just a list of packages in stable?

**Comment by na4zagin3** [comment]
Thanks! That means “packages for the latest stable version of SATySFi.” I'm sorry if you are confused.

P.S. I recommend to add library documents in the next release so that CI can ensure your package is not broken by upstream changes (e.g., new development/stable versions of SATySFi)

**Comment by yuhr** [comment]
Okay, I see. Thank you!

**Comment by na4zagin3** [comment]
Awesome!

**Pull request merged**
