### PR TITLE
Package satysfi-matrixcd.0.0.1

### PR DESCRIPTION
**Pull request by abenori**
### `satysfi-matrixcd.0.0.1`
A package for SATySFi to draw commutative diagrams

---
* Homepage: https://github.com/abenori/satysfi-matrixcd/
* Source repo: git+https://github.com/abenori/satysfi-matrixcd.git
* Bug tracker: https://github.com/abenori/satysfi-matrixcd/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by na4zagin3** [comment]
@abenori Thank you for sending the package!
Can you please add dependency on `satysfi-base` to Satyristes as well?
https://github.com/abenori/satysfi-matrixcd/blob/8e2bf62e19d4b3c872fa646867400f9cac431f73/Satyristes#L10

**Comment by abenori** [comment]
Thank you. I fixed it in my repository 
https://github.com/abenori/satysfi-matrixcd/commit/32e4f16b8f3141bb6563012c7874d3a28f7f6b66
Could you tell me what I should do next?

**Comment by na4zagin3** [comment]
Nice!

Hmm, could you please release a new version? Although, technically, you can apply patches to non-OPAM files (v. https://opam.ocaml.org/doc/Manual.html#opamfield-patches), that’s only as a last resort.

Additionally, I would highly recommend that specify version constrains in OPAM file.

I will automatically extend the version constraints of libraries registered in the snapshots as long as they are successfully built.  Therefore I also encourage people to add the document packages with examples to detect compile errors; in addition to that, it will be available at <https://satyrographos-packages.netlify.app/>.

(FYI, for visual or function degradation, Satyrographos 0.0.3 will have a new package type for test cases.)

**Comment by abenori** [comment]
Thank you! I specified versions and did publish again.

**Comment by na4zagin3** [comment]
Thanks!

**Pull request merged**
