### PR TITLE
2 packages from monaqa/satysfi-easytable at 1.0.0

### PR DESCRIPTION
**Pull request by monaqa**
A SATySFi package to build simple tables

This pull-request concerns:
-`satysfi-easytable.1.0.0`
-`satysfi-easytable-doc.1.0.0`

---
* Homepage: https://github.com/monaqa/satysfi-easytable
* Source repo: git+https://github.com/monaqa/satysfi-easytable.git
* Bug tracker: https://github.com/monaqa/satysfi-easytable/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by na4zagin3** [comment]
Good job!  BTW, do you mind to update snapshot files (i.e., `/satyrographos-repo-test-develop.opam`, `satyrographos-repo-test-stable-0-0-4.opam`, and `satyrographos-repo-test-stable-0-0-5.opam`)?

I'm planning to have CI automatically test new versions introduced by PRs, but it's not ready yet..

**Comment by monaqa** [comment]
Thanks!

I updated the snapshot files, `satyrographos-repo-test-develop.opam` and `satyrographos-repo-test-stable-0-0-5.opam`.
I didn't add easytable package to `satyrographos-repo-test-stable-0-0-4.opam`, because `easytable package` and its document don't support SATySFi v0.0.4.

**Comment by na4zagin3** [comment]
Nice! But the build failed. It looks like [`Satyristes`](https://github.com/monaqa/satysfi-easytable/blob/091046f143304f4d12e9f2170021fc0d0c86e888/Satyristes#L26) lacks dependency on `enumitem`.

```
- Setting up SATySFi env at /tmp/Satyrographos30964abuild_opam 
- satysfi out>  ---- ---- ---- ----
- satysfi out>   target file: 'easytable.pdf'
- satysfi out>   dump file: 'easytable.satysfi-aux' (will be created)
- satysfi out>   parsing 'easytable.saty' ...
- satysfi out>   parsing 'stdjabook.satyh' ...
- satysfi out>   parsing 'pervasives.satyh' ...
- satysfi out>   parsing 'gr.satyh' ...
- satysfi out>   parsing 'geom.satyh' ...
- satysfi out>   parsing 'list.satyg' ...
- satysfi out>   parsing 'option.satyg' ...
- satysfi out>   parsing 'math.satyh' ...
- satysfi out>   parsing 'code.satyh' ...
- satysfi out>   parsing 'color.satyh' ...
- satysfi out>   parsing 'vdecoset.satyh' ...
- satysfi out>   parsing 'annot.satyh' ...
- satysfi out>   parsing 'footnote-scheme.satyh' ...
- satysfi out>   parsing 'hdecoset.satyh' ...
- satysfi out> ! [Error] package file not found:
- satysfi out>       enumitem/enumitem
- satysfi out>     candidate paths:
- satysfi out>       /tmp/Satyrographos30964abuild_opam/local/packages/enumitem/enumitem.satyh
- satysfi out>       /tmp/Satyrographos30964abuild_opam/local/packages/enumitem/enumitem.satyg
- satysfi out>       /home/travis/.satysfi/local/packages/enumitem/enumitem.satyh
- satysfi out>       /home/travis/.satysfi/local/packages/enumitem/enumitem.satyg
- satysfi out>       /usr/local/share/satysfi/local/packages/enumitem/enumitem.satyh
- satysfi out>       /usr/local/share/satysfi/local/packages/enumitem/enumitem.satyg
- satysfi out>       /usr/share/satysfi/local/packages/enumitem/enumitem.satyh
- satysfi out>       /usr/share/satysfi/local/packages/enumitem/enumitem.satyg
- satysfi out>       /tmp/Satyrographos30964abuild_opam/dist/packages/enumitem/enumitem.satyh
- satysfi out>       /tmp/Satyrographos30964abuild_opam/dist/packages/enumitem/enumitem.satyg
- satysfi out>       /home/travis/.satysfi/dist/packages/enumitem/enumitem.satyh
- satysfi out>       /home/travis/.satysfi/dist/packages/enumitem/enumitem.satyg
- satysfi out>       /usr/local/share/satysfi/dist/packages/enumitem/enumitem.satyh
- satysfi out>       /usr/local/share/satysfi/dist/packages/enumitem/enumitem.satyg
- satysfi out>       /usr/share/satysfi/dist/packages/enumitem/enumitem.satyh
- satysfi out>       /usr/share/satysfi/dist/packages/enumitem/enumitem.satyg
```

Do you want to add a patch to this repo or fix it in upstream?

**Comment by na4zagin3** [comment]
Thank you!!

**Pull request merged**
