### PR TITLE
2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.2

### PR DESCRIPTION
**Pull request by zeptometer**
This pull-request concerns:
-`satysfi-class-yabaitech.0.0.2`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.2`: Document: The yabaitech.tokyo SATySFi class file

---
* Homepage: https://github.com/yabaitechtokyo/satysfi-class-yabaitech
* Source repo: git+https://github.com/yabaitechtokyo/satysfi-class-yabaitech.git
* Bug tracker: https://github.com/yabaitechtokyo/satysfi-class-yabaitech/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by na4zagin3** [comment]
Hmm, update-snapshot does not work well, I think.  Could you revert the last commit, pull `master` from origin, and re-run update-snapshot?

**Comment by na4zagin3** [comment]
And, do you mind tell me the result of `git remote -v`?

**Comment by na4zagin3** [comment]
Ahh, I see your problem.  Your fork's master is old..

**Comment by na4zagin3** [comment]
@zeptometer I updated the instruction.  Do you mind to follow that again?

**Comment by zeptometer** [comment]
Seems I should have pulled the latest master from upstream?
```
$ git remote -v
origin  git@github.com:zeptometer/satyrographos-repo.git (fetch)
origin  git@github.com:zeptometer/satyrographos-repo.git (push)
upstream        https://github.com/na4zagin3/satyrographos-repo.git (fetch)
upstream        https://github.com/na4zagin3/satyrographos-repo.git (push)
```

**Comment by zeptometer** [comment]
> @zeptometer I updated the instruction. Do you mind to follow that again?

Thanks, I'll check it out.

**Comment by zeptometer** [comment]
@na4zagin3 I've rerun `opam publish` and then followed the instruction. Hoping I don't miss anything 🤞

**Comment by zeptometer** [comment]
The current build failure is due to a misconfiguration of satysfi-class-yabaitech-doc.opam. I'll fix and push it.

**Comment by na4zagin3** [comment]
@zeptometer thanks!  And could you please rebase onto master once #155 is merged?  I just realize the sorting order of packages depended on user's locale.  #155 will address the problem.

**Comment by na4zagin3** [comment]
Thank you! Merging.

**Pull request merged**
