### PR TITLE
2 packages from monaqa/satysfi-easytable at 1.1.0

### PR DESCRIPTION
**Pull request by monaqa**
A SATySFi package to build simple tables

This pull-request concerns:
-`satysfi-easytable.1.1.0`
-`satysfi-easytable-doc.1.1.0`

---
* Homepage: https://github.com/monaqa/satysfi-easytable
* Source repo: git+https://github.com/monaqa/satysfi-easytable.git
* Bug tracker: https://github.com/monaqa/satysfi-easytable/issues

---
:camel: Pull-request generated by opam-publish v2.0.3
# Automatic follow-ups
Choose follow-up actions.  Do not write anything after this section.
- Add to snapshot `snapshot-develop`
- Add to snapshot `snapshot-stable-0-0-4`
- Add to snapshot `snapshot-stable-0-0-5`
- Add to snapshot `snapshot-stable-0-0-6`

### CODE REVIEW

**Comment by na4zagin3** [comment]
I don't know what happened.  Let me rerun the CI with reopening this pr.

**Comment by monaqa** [comment]
https://github.com/na4zagin3/satyrographos-repo/pull/281/checks?check_run_id=1848442478#step:10:250

Hmm... `table-builder.satyh` is a new file added in v1.1.0 (this release), and did not exist in v1.0.0.
Does that have anything to do with the cause of this error?

**Comment by monaqa** [comment]
Oops! Sorry, my fault.

**Comment by monaqa** [comment]
I will release `v1.1.1` after making sure that there are no errors with linter. Thanks!

**Pull request closed without merging**
