### PR TITLE
2 packages from zeptometer/SATySFi-fonts-asana at 000.958+1+satysfi0.0.4

### PR DESCRIPTION
**Pull request by zeptometer**
This pull-request concerns:
-`satysfi-fonts-asana-math.000.958+1+satysfi0.0.4`: SATySFi Font Package for Asana Math Fonts
-`satysfi-fonts-asana-math-doc.000.958+1+satysfi0.0.4`: Document of SATySFi Font Package for Asana Math Fonts

---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-asana-math
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-asana-math.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-asana-math/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by na4zagin3** [comment]
Can you revert https://github.com/na4zagin3/satyrographos-repo/pull/101 in this PR?

**Comment by na4zagin3** [comment]
And, if possible, could you add [archive-mirrors](https://opam.ocaml.org/doc/Manual.html#repofield-archive-mirrors) so that the package works even after a new version is released?
I created a mirror at https://github.com/na4zagin3/satysfi-dist-font-archives/tree/master/Asana-Math/2019-04-14

**Comment by zeptometer** [comment]
Gotcha, I'll support archive-mirrors with a new version with separate PR.

**Comment by zeptometer** [comment]
Created issue: https://github.com/zeptometer/SATySFi-fonts-asana-math/issues/1

**Comment by na4zagin3** [comment]
Thanks! IMO, you don't need to give another version for adding mirrors because that does not change any installation result and should not regress. Apparently it's normal to update OPAM files in OPAM repositories. (OPAM file for Satyrographos stored in the official OPAM repository has been edited by the OPAM maintainers a few times.)

**Comment by na4zagin3** [comment]
Thanks!

**Pull request merged**
