### PR TITLE
2 packages from zeptometer/SATySFi-fonts-computer-modern at 0.7.0+satysfi0.0.4

### PR DESCRIPTION
**Pull request by zeptometer**
This pull-request concerns:
-`satysfi-fonts-computer-modern.0.7.0+satysfi0.0.4`: SATySFi Font Package for Donald Knuth's Computer Modern Fonts
-`satysfi-fonts-computer-modern-doc.0.7.0+satysfi0.0.4`: Document of SATySFi Font Package for Donald Knuth's Computer Modern Fonts

---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-computer-modern
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-computer-modern.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-computer-modern/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by na4zagin3** [comment]
I'm curious. Aren't the fontname be Computer Modern Unicode or cm-unicode?

**Comment by zeptometer** [comment]
I'm just using the name from https://www.checkmyworking.com/cm-web-fonts/ and don't have a strong preference for it. Shall I rename them?

**Comment by na4zagin3** [comment]
Hmm, it confuses me. The site claims their fonts are based on cm-unicode and modified for browsers by generating several webfont formats and dropping glyphs. As fonts for typesetting software, unlike web fonts, usually do not have to limit number of glyphs, because of subset font embedding, can you simply use cm-unicode instead, rather than a trimmed version?

> The cm-unicode project compiles versions of the Computer Modern fonts in a few formats, including TTF. I've run them through codeandmore's \@font-face kit generator and FontSquirrel to get all the weird formats that the various browsers insist on. This page shows off each typeface, with links to packages containing everything you need to use them in your own pages.

> I've taken a largish subset of the characters available from each font to make them a sensible size for use on the web. The biggest TTF fonts are around 100k compressed. Each font is given in four formats, but only one will be downloaded by the user, depending on which browser they're using. with modification

https://www.checkmyworking.com/cm-web-fonts/

**Comment by zeptometer** [comment]
Ah, as to the font archive origin, I just did monkey work to find it i.e. google 'computer modern' and click the top result...

> can you simply use cm-unicode instead, rather than a trimmed version?

Yeah, your point is right. I should use fonts from https://sourceforge.net/projects/cm-unicode/ 
(which looks the right place to download cm-unicode fonts) instead.

**Comment by na4zagin3** [comment]
I just downloaded Serif series from the website and found out that .ttf files could be unchanged from what cm-unicode distributes. And their font names claims the family name is `CMU Serif`, I strongly recommend to use materials directly from [cm-unicode](https://cm-unicode.sourceforge.io/).

**Comment by zeptometer** [comment]
Moved the PR to #66

**Pull request closed without merging**
