### PR TITLE
2 packages from monaqa/satysfi-enumitem at 3.0.0

### PR DESCRIPTION
**Pull request by monaqa**
A SATySFi package for creating itemized lists

This pull-request concerns:
-`satysfi-enumitem.3.0.0`
-`satysfi-enumitem-doc.3.0.0`

---
* Homepage: https://github.com/monaqa/satysfi-enumitem
* Source repo: git+https://github.com/monaqa/satysfi-enumitem.git
* Bug tracker: https://github.com/monaqa/satysfi-enumitem/issues

---
:camel: Pull-request generated by opam-publish v2.0.3
# Automatic follow-ups
Choose follow-up actions.  Do not write anything after this section.
- Add to snapshot `snapshot-develop`
- Add to snapshot `snapshot-stable-0-0-4`
- ~~Add to snapshot `snapshot-stable-0-0-5`~~ (Inconsistent)
- Add to snapshot `snapshot-stable-0-0-6`

### CODE REVIEW

**Comment by na4zagin3** [comment]
@monaqa 
`satysfi-enumitem-doc.3.0.0` does not compile on SATySFi 0.0.6.

```
  target file: 'enumitem.pdf'
  dump file: 'enumitem.satysfi-aux' (will be created)
  parsing 'enumitem.saty' ...
! [Syntax Error at Lexer] at "enumitem.saty", line 895, characters 64-65:
    illegal token '(' in a math area
```

Line 895 is here:

```
        * Lebesgue 測度の劣加法性より（中略）、${m(A) = m(B)} が示された。
```

Can you either fix the version constraint on SATySFi or fix the problematic lines?

Furthermore, `satysfi-enumitem.3.0.0` is not coherent with the currently available versions of `satysfi-class-slydifi`, `satysfi-class-slydifi-doc`, and so on.  I can add your package to new snapshots.  Which SATySFi versions do you want to cut down new snapshots? 

for example, `satysfi-azmath-doc.0.0.3` fails with
```
! [Type Error] at "azmath.saty", line 492, character 16 to line 521, character 5:
    this expression has type
      itemize,
    but is expected of type
      block-text.
    This constraint is required by the expression
    at "enumitem.satyh", line 377, characters 24-34.
```

**Comment by na4zagin3** [comment]
FYI, the following packages will be broken with the new version of `enumitem`, according to https://satyrographos-packages.netlify.app/packages/enumitem/reverse-dependencies:

- azmath-doc
- class-slydifi
- easytable-doc
- enumitem-doc
- figbox-doc

**Comment by monaqa** [comment]
Thank you for the reply. I have released [the fixed version 3.0.1](https://github.com/na4zagin3/satyrographos-repo/pull/387).

> FYI, the following packages will be broken with the new version of enumitem,

Is it enough to release a modified version of each package to match the latest enumitem package?

**Comment by na4zagin3** [comment]
Thank you!  I'll merge ver 3.0.1.
I'll cut down a new snapshot later.

> Is it enough to release a modified version of each package to match the latest enumitem package?

You'll want to rewrite the doc packages with the new version of enumitem too because of the API changes.

**Comment by na4zagin3** [comment]
Let me rerun the CI. Now it should fail.

**Comment by na4zagin3** [comment]
Closing this PR as enumitem 3.0.1 has been merged
https://github.com/na4zagin3/satyrographos-repo/pull/387

**Pull request closed without merging**
