### PR TITLE
Fix core_kernel version of satysfi

### PR DESCRIPTION
**Pull request by yasuo-ozu**
Fix core_kernel version of satysfi

# Automatic follow-ups
Choose follow-up actions.  Do not write anything after this section.
- ~~Add to snapshot `snapshot-develop`~~ (No updates)
- ~~Add to snapshot `snapshot-develop--1`~~ (No updates)
- ~~Add to snapshot `snapshot-stable-0-0-4`~~ (No updates)
- ~~Add to snapshot `snapshot-stable-0-0-5`~~ (No updates)
- ~~Add to snapshot `snapshot-stable-0-0-6`~~ (No updates)
- ~~Add to snapshot `snapshot-stable-0-0-6--1`~~ (No updates)

### CODE REVIEW

**Comment by yasuo-ozu** [comment]
ref

https://twitter.com/yasuo_ozu/status/1506258738323521538

**Comment by yasuo-ozu** [comment]
@na4zagin3 
Excuse me, but could you make some effort with this PR?
It fixes the unconsistency SATySFi installation both local and CI environment.

**Comment by na4zagin3** [comment]
Thank you very much for updating the version constraint!  I'm merging this.

**Comment by na4zagin3** [comment]
I'm sorry for my late reply..

**Pull request merged**
