### PR TITLE
7 packages from MasWag/satyrographos-repo at satysfi-class-cv-0.1.1

### PR DESCRIPTION
**Pull request by MasWag**
This pull-request concerns:
-satysfi-class-cv.0.1.1: SATySFi class file for Curriculum Vitae
-satysfi-class-cv-doc.0.1.1: Documentation of a class for CV

Homepage: https://github.com/MasWag/cv-satysfi
Source repo: git+https://github.com/MasWag/cv-satysfi.git
Bug tracker: https://github.com/MasWag/cv-satysfi/issues
# Automatic follow-ups
Choose follow-up actions.  Do not write anything after this section.
- [ ] Add to snapshot `snapshot-develop` :: satysfi-class-cv-doc.0.1.1 satysfi-class-cv.0.1.1
- ~~Add to snapshot `snapshot-stable-0-0-4`~~ (Inconsistent)
- ~~Add to snapshot `snapshot-stable-0-0-5`~~ (Inconsistent)
- [ ] Add to snapshot `snapshot-stable-0-0-6` :: satysfi-class-cv-doc.0.1.1 satysfi-class-cv.0.1.1
- [ ] Add to snapshot `snapshot-stable-0-0-6--1` :: satysfi-class-cv-doc.0.1.1 satysfi-class-cv.0.1.1
- [ ] Add to snapshot `snapshot-stable-0-0-7` :: satysfi-class-cv-doc.0.1.1 satysfi-class-cv.0.1.1
- [ ] Add to snapshot `snapshot-stable-0-0-8` :: satysfi-class-cv-doc.0.1.1 satysfi-class-cv.0.1.1

### CODE REVIEW

**Comment by na4zagin3** [comment]
Thank you for sending a PR!

Well, can you tell me how you created this?  The committed changes don't look correct.
I expect new files `packages/satysfi-class-cv/satysfi-class-cv.0.1.1/opam` and `packages/satysfi-class-cv-doc/satysfi-class-cv-doc.0.1.1/opam` instead.

**Comment by MasWag** [comment]
Sorry for bothering you. I did not notice it. I made this PR as follows:

1. I https://twitter.com/pickoba/status/1527933931374317569?s=20 ran `opam publish` but it failed with this error message https://twitter.com/pickoba/status/1527933931374317569?s=20 
2. I manually made a PR using the branch made by opam publish. But maybe I made some mistakes in this step.

I will push the intended commit to this branch later.

**Comment by na4zagin3** [comment]
Thank you for sharing that!  I'm not bothered at all :grinning: 

Hmm, I should tackle the issue as it's painful to manually create a MR.  Let me do that when I have time.

> I will push the intended commit to this branch later

Thank you so much!

FYI, `packages/satysfi-class-cv/satysfi-class-cv.0.1.1/opam` will contain fields from https://github.com/MasWag/cv-satysfi/blob/master/satysfi-class-cv.opam except for field `version`, with additional field `url`

```opam
url {
  src:
    "https://github.com/MasWag/satyrographos-repo/archive/refs/tags/satysfi-class-cv-0.1.1.tar.gz"
  checksum: [
    "md5=89d66fb4763759d58989b3d7fc1dc622"
    "sha512=9fd2db9d559410731a996bdf7d51e823ec9a0fdff113a44740dd5b198911d5c95c72f187c71c6244da31deb5aca20b2a95cc906254d6dd351677750c24cbeaff"
  ]
}
```

**Comment by MasWag** [comment]
I merged the change, but the CI did not pass. Do I need some fixes?

**Comment by na4zagin3** [comment]
@MasWag thank you for updating!  Can you please remove changes `packages/snapshot-*/**/*`?  I guess they are mistakenly created by some reason.

**Comment by MasWag** [comment]
Thanks. I removed/rebased the changes packages/snapshot-*/**/.

**Comment by na4zagin3** [comment]
Perfect!  Thank you!

**Pull request merged**
