### PR TITLE
2 packages from zeptometer/SATySFi-fonts-dejavu at 2.37

### PR DESCRIPTION
**Pull request by zeptometer**
This pull-request concerns:
-`satysfi-fonts-dejavu.2.37`: SATySFi Font Package for DejaVu Fonts
-`satysfi-fonts-dejavu-doc.2.37`: Document of SATySFi Font Package for DejaVu Fonts

---
* Homepage: https://github.com/zeptometer/SATySFi-fonts-dejavu
* Source repo: git+https://github.com/zeptometer/SATySFi-fonts-dejavu.git
* Bug tracker: https://github.com/zeptometer/SATySFi-fonts-dejavu/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by zeptometer** [comment]
Ah sorry, could you please wait reviewing this until https://github.com/zeptometer/SATySFi-fonts-dejavu/issues/1 is done?

**Comment by zeptometer** [comment]
@na4zagin3 Now it's ready for review again!

**Comment by na4zagin3** [comment]
@zeptometer Could you add `satysfi-fonts-dejavu` and `satysfi-fonts-dejavu-doc` to [`.travis.yml`](https://github.com/na4zagin3/satyrographos-repo/blob/de1f0ab4831952ca3bd192d696bbd3fc49c2a703/.travis.yml#L16)?

**Comment by zeptometer** [comment]
Done 👍

**Comment by na4zagin3** [comment]
Thanks!

**Pull request merged**
